export const MOCK_VOCAB_DATA = {
    "n3-verb-1": {
      id: "n3-verb-1",
      title: "Động từ N3 - Nhóm 1",
      words: [
        { id: 'w1', kanji: '開発', hiragana: 'かいはつ', meaning: 'Phát triển' },
        { id: 'w2', kanji: '改善', hiragana: 'かいぜん', meaning: 'Cải thiện' },
        { id: 'w3', kanji: '確認', hiragana: 'かくにん', meaning: 'Xác nhận' },
        { id: 'w4', kanji: '計画', hiragana: 'けいかく', meaning: 'Kế hoạch' },
        { id: 'w5', kanji: '経験', hiragana: 'けいけん', meaning: 'Kinh nghiệm' },
        { id: 'w6', kanji: '整理', hiragana: 'せいり', meaning: 'Chỉnh sửa, thanh lý' },
        { id: 'w7', kanji: '相談', hiragana: 'そうだん', meaning: 'Thảo luận, bàn bạc' },
        { id: 'w8', kanji: '準備', hiragana: 'じゅんび', meaning: 'Chuẩn bị' },
        { id: 'w9', kanji: '心配', hiragana: 'しんぱい', meaning: 'Lo lắng' },
        { id: 'w10', kanji: '説明', hiragana: 'せつめい', meaning: 'Giải thích' },
        { id: 'w11', kanji: '紹介', hiragana: 'しょうかい', meaning: 'Giới thiệu' },
        { id: 'w12', kanji: '見学', hiragana: 'けんがく', meaning: 'Tham quan học tập' },
        { id: 'w13', kanji: '注意', hiragana: 'ちゅうい', meaning: 'Chú ý' },
        { id: 'w14', kanji: '反対', hiragana: 'はんたい', meaning: 'Phản đối' },
        { id: 'w15', kanji: '変更', hiragana: 'へんこう', meaning: 'Thay đổi' },
        { id: 'w16', kanji: '連絡', hiragana: 'れんらく', meaning: 'Liên lạc' },
        { id: 'w17', kanji: '希望', hiragana: 'きぼう', meaning: 'Hy vọng' },
        { id: 'w18', kanji: '予約', hiragana: 'よやく', meaning: 'Đặt trước' },
        { id: 'w19', kanji: '参加', hiragana: 'さんか', meaning: 'Tham gia' },
        { id: 'w20', kanji: '失敗', hiragana: 'しっぱい', meaning: 'Thất bại' },
        { id: 'w21', kanji: '成功', hiragana: 'せいこう', meaning: 'Thành công' },
        { id: 'w22', kanji: '合格', hiragana: 'ごうかく', meaning: 'Đỗ, vượt qua' },
        { id: 'w23', kanji: '復習', hiragana: 'ふくしゅう', meaning: 'Ôn tập' },
        { id: 'w24', kanji: '予習', hiragana: 'よしゅう', meaning: 'Chuẩn bị bài' },
        { id: 'w25', kanji: '感謝', hiragana: 'かんしゃ', meaning: 'Cảm ơn, cảm tạ' },
        { id: 'w26', kanji: '協力', hiragana: 'きょうりょく', meaning: 'Hợp tác' },
        { id: 'w27', kanji: '移動', hiragana: 'いどう', meaning: 'Di chuyển' },
        { id: 'w28', kanji: '延期', hiragana: 'えんき', meaning: 'Trì hoãn' },
        { id: 'w29', kanji: '中止', hiragana: 'ちゅうし', meaning: 'Hoãn, dừng' },
        { id: 'w30', kanji: '解決', hiragana: 'かいけつ', meaning: 'Giải quyết' },
        { id: 'w31', kanji: '応援', hiragana: 'おうえん', meaning: 'Cổ vũ' },
        { id: 'w32', kanji: '修理', hiragana: 'しゅうり', meaning: 'Sửa chữa' },
        { id: 'w33', kanji: '集中', hiragana: 'しゅうちゅう', meaning: 'Tập trung' },
        { id: 'w34', kanji: '報告', hiragana: 'ほうこく', meaning: 'Báo cáo' },
        { id: 'w35', kanji: '保存', hiragana: 'ほぞん', meaning: 'Lưu trữ' },
        { id: 'w36', kanji: '翻訳', hiragana: 'ほんやく', meaning: 'Biên dịch' },
        { id: 'w37', kanji: '通訳', hiragana: 'つうやく', meaning: 'Thông dịch' },
        { id: 'w38', kanji: '我慢', hiragana: 'がまん', meaning: 'Chịu đựng' },
        { id: 'w39', kanji: '期待', hiragana: 'きたい', meaning: 'Kỳ vọng' },
        { id: 'w40', kanji: '満足', hiragana: 'まんぞく', meaning: 'Hài lòng' }
      ]
    }
  };